services:
  app:
    build: .
    container_name: app
    restart: always
    depends_on:
      - db
      - redis
      - rabbitmq
      - minio
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_BACKEND_URL: ${CELERY_BACKEND_URL}
      MINIO_URL: ${MINIO_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: |
      bash -c "
      poetry run alembic upgrade head &&
      poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  celery:
    build: .
    container_name: celery
    restart: always
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_BACKEND_URL: ${CELERY_BACKEND_URL}
    env_file:
      - .env
    command: ["poetry", "run", "celery", "-A", "app.tasks", "worker", "--loglevel=info"]

  db:
    image: postgres:15
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9090:9090"
    command: ["server", "/data", "--console-address", ":9090"]
    volumes:
      - minio_data:/data

  sftp:
    image: atmoz/sftp
    container_name: sftp
    ports:
      - "2222:22"
    volumes:
      - ./sftp_data:/home/joeroot/upload
    environment:
      - SFTP_USERS=joeroot:password:1111

  celery-beat:
    build: .
    container_name: celery-beat
    restart: always
    depends_on:
      - celery
      - redis
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    command: [ "poetry", "run", "celery", "-A", "app.tasks", "beat", "--loglevel=info" ]

volumes:
  postgres_data:
  minio_data: